Repository halo-dev/console, pull requests merged in 2020-09, with the labels that each got.

#242 fix: #241
  src/views/post/PostEdit.vue
  src/views/sheet/SheetEdit.vue
Labels: bug

#244 feat: halo#1065
  src/api/admin.js
  src/views/system/developer/DeveloperOptions.vue
  src/views/system/developer/tabs/ApplicationConfig.vue
Labels: enhancement

#243 feat: add smtp form validation.
  package-lock.json
  package.json
  src/views/system/optiontabs/ApiTab.vue
  src/views/system/optiontabs/AttachmentTab.vue
  src/views/system/optiontabs/CommentTab.vue
  src/views/system/optiontabs/PostTab.vue
  src/views/system/optiontabs/SmtpTab.vue
  tailwind.config.js
Labels: enhancement

#245 Remove float more actions
  package-lock.json
  package.json
  src/components/PageHeader/PageHeader.vue
  src/components/PageHeader/index.js
  src/components/Tools/Breadcrumb.vue
  src/config/router.config.js
  src/core/lazy_lib/components_use.js
  src/layouts/PageView.vue
  src/views/interface/MenuList.vue
  src/views/interface/ThemeEdit.vue
  src/views/interface/ThemeList.vue
Labels: enhancement

#248 fix: #247
  src/views/post/components/PostSettingDrawer.vue
  src/views/sheet/components/SheetSettingDrawer.vue
Labels: bug

#249 refactor: theme remote install.
  src/core/lazy_lib/components_use.js
  src/views/interface/ThemeList.vue
Labels: enhancement

#250 refactor: form verification.
  src/components/global.less
  src/views/sheet/independent/JournalList.vue
  src/views/system/developer/tabs/OptionsList.vue
  src/views/system/developer/tabs/RuntimeLogs.vue
  src/views/system/developer/tabs/StaticStorage.vue
Labels: enhancement

#251 refactor: system options page layout.
  src/components/Editor/MarkdownEditor.vue
  src/config/router.config.js
  src/layouts/PageView.vue
  src/views/attachment/components/AttachmentDetailDrawer.vue
  src/views/comment/components/CommentTab.vue
  src/views/comment/components/TargetCommentDrawer.vue
  src/views/interface/ThemeList.vue
  src/views/sheet/independent/JournalList.vue
  src/views/system/About.vue
  src/views/system/SystemOptions.vue
  src/views/system/ToolList.vue
  src/views/system/developer/DeveloperOptions.vue
  src/views/system/developer/tabs/OptionsList.vue
Labels: enhancement

#252 release: 1.4.0
  .env.jsdelivr
  package-lock.json
  package.json
  public/index.html
Labels: enhancement

#254 fix: content block padding error.
  src/layouts/PageView.vue
  src/views/interface/ThemeList.vue
  src/views/system/SystemOptions.vue
Labels: bug

#256 chore: remove moment dependency.
  package-lock.json
  package.json
  src/utils/datetime.js
  src/utils/filter.js
  src/utils/util.js
  src/views/post/PostEdit.vue
  src/views/post/components/PostSettingDrawer.vue
  src/views/sheet/SheetEdit.vue
  src/views/sheet/components/SheetSettingDrawer.vue
  src/views/system/developer/tabs/RuntimeLogs.vue
  vue.config.js
Labels: dependencies

#257 fix: #247
  src/views/post/components/PostSettingDrawer.vue
  src/views/sheet/components/SheetSettingDrawer.vue
Labels: bug

#258 refactor: photo manage.
  src/views/interface/MenuList.vue
  src/views/sheet/independent/LinkList.vue
  src/views/sheet/independent/PhotoList.vue
Labels: enhancement
