Repository halo-dev/console, pull requests merged in 2022-07, with the labels that each got.

#584 chore: bump editor version to 3.0.5
  package.json
  pnpm-lock.yaml
Labels: release-note, approved, lgtm, kind/improvement

#585 Automated cherry pick of #584: chore: bump editor version to 3.0.5
  package.json
  pnpm-lock.yaml
Labels: approved, lgtm

#586 release: 1.5.4
  package.json
Labels: release-note-none, approved, lgtm

#587 feat: add cleanup tags support
  pnpm-lock.yaml
  src/components/Post/PostTag.vue
  src/views/post/TagList.vue
Labels: kind/feature, release-note, approved, lgtm

#588 Add dockerignore file to ignore node_modules folder while building docker image
  .dockerignore
Labels: release-note-none, approved, lgtm, kind/improvement

#589 Add build-push job for Halo admin
  .github/workflows/main.yml
  Dockerfile
Labels: kind/feature, release-note-none, approved, lgtm

#590 feat: add support for uploading plugins
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/modules/system/plugins/PluginList.vue
  src/modules/system/plugins/components/PluginInstallModal.vue
Labels: kind/feature, release-note-none, approved, lgtm

#591 feat: api supports field filtering
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/roles/composables/use-role.ts
Labels: kind/feature, release-note-none, approved, lgtm
