Repository halo-dev/console, pull requests merged in 2022-11, with the labels that each got.

#672 feat: add formkit custom input of codemirror
  docs/custom-formkit-input/README.md
  src/formkit/formkit.config.ts
  src/formkit/inputs/code/CodeInput.vue
  src/formkit/inputs/code/index.ts
Labels: kind/feature, release-note, approved, lgtm

#674 feat: add formkit custom input of attachment
  docs/custom-formkit-input/README.md
  src/formkit/formkit.config.ts
  src/formkit/inputs/attachment/AttachmentInput.vue
  src/formkit/inputs/attachment/index.ts
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/system/users/components/UserEditingModal.vue
Labels: kind/feature, release-note, approved, lgtm

#675 feat: add preset language support for codemirror components
  packages/components/package.json
  packages/components/src/components/codemirror/Codemirror.story.vue
  packages/components/src/components/codemirror/Codemirror.vue
  pnpm-lock.yaml
Labels: kind/feature, release-note-none, approved, lgtm

#676 fix: show publish time instead of creation time for post list
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
Labels: kind/bug, release-note, approved, lgtm

#671 feat: add setup post/singlePage/category custom templates support
  package.json
  pnpm-lock.yaml
  src/components/global-search/GlobalSearchModal.vue
  src/main.ts
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/categories/components/__tests__/CategoryEditingModal.spec.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/components/__tests__/PostSettingModal.spec.ts
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/stores/counter.ts
  src/stores/theme.ts
Labels: kind/feature, release-note, approved, lgtm

#677 feat: support for managing recycle bin posts and single pages
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/module.ts
Labels: kind/feature, release-note, approved, lgtm

#678 refactor: update the field of the plugin logo
  package.json
  pnpm-lock.yaml
  src/components/global-search/GlobalSearchModal.vue
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#679 fix: some vue warn in browser dev console
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#681 perf: optimize the creation of attachment storage policies
  packages/components/src/components/alert/Alert.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment-policy.ts
Labels: release-note, approved, lgtm, kind/improvement

#680 perf: optimize the style of fieldset in the form
  src/formkit/theme.ts
Labels: release-note, approved, lgtm, kind/improvement

#682 chore: release 2.0.0-alpha.4
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#683 perf: improve theme preview modal
  packages/components/src/components/modal/Modal.vue
  packages/components/src/components/tabs/Tabbar.story.vue
  packages/components/src/components/tabs/Tabbar.vue
  packages/components/src/icons/icons.ts
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/interface/themes/Visual.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/components/preview/ThemeListItem.vue
  src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/interface/themes/module.ts
Labels: release-note, approved, lgtm, kind/improvement

#686 refactor: refactoring the logic for get the setup state of the system
  src/main.ts
  src/router/guards/check-states.ts
  src/views/system/Setup.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#684 feat: add setup primary menu support
  src/modules/interface/menus/components/MenuList.vue
  src/views/system/setup-data/menu.json
Labels: kind/feature, release-note, approved, lgtm

#670 refactor: post editor
  package.json
  pnpm-lock.yaml
  src/components/editor/DefaultEditor.vue
  src/components/global-search/GlobalSearchModal.vue
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#685 refactor: post and singlePage publishing
  package.json
  packages/components/src/components/status/StatusDot.vue
  packages/components/src/icons/icons.ts
  pnpm-lock.yaml
  src/constants/labels.ts
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/dashboard/widgets/RecentPublishedWidget.vue
  src/views/system/Setup.vue
  src/views/system/setup-data/post.json
  src/views/system/setup-data/singlePage.json
Labels: release-note-none, approved, lgtm, kind/improvement

#687 refactor: remove formkit auto-animate addon
  package.json
  pnpm-lock.yaml
  src/formkit/formkit.config.ts
  src/formkit/theme.ts
Labels: release-note, approved, lgtm, kind/improvement

#690 refactor: post publishing
  package.json
  pnpm-lock.yaml
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/users/UserList.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#691 chore: release 2.0.0-beta.1
  package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#692 feat: add formkit custom input of repeater
  docs/custom-formkit-input/README.md
  package.json
  packages/components/src/components/button/Button.vue
  packages/components/src/components/button/__tests__/__snapshots__/Button.spec.ts.snap
  packages/components/src/components/empty/__tests__/__snapshots__/Empty.spec.ts.snap
  packages/components/src/icons/icons.ts
  pnpm-lock.yaml
  src/formkit/formkit.config.ts
  src/formkit/inputs/repeater/Repeater.vue
  src/formkit/inputs/repeater/index.ts
  src/formkit/inputs/repeater/sections/index.ts
  src/formkit/plugins/radio-alt.ts
  src/formkit/theme.ts
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  src/modules/system/plugins/PluginSetting.vue
  src/modules/system/settings/SystemSetting.vue
Labels: kind/feature, release-note, approved, lgtm

#689 chore: bump dependencies
  package.json
  packages/components/package.json
  packages/components/src/components/avatar/Avatar.vue
  packages/components/src/components/dialog/Dialog.vue
  packages/components/src/components/empty/__tests__/Empty.spec.ts
  packages/components/src/components/empty/__tests__/__snapshots__/Empty.spec.ts.snap
  packages/shared/package.json
  pnpm-lock.yaml
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyCreationModal.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/system/users/components/GrantPermissionModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#694 feat: attachment management support sorting
  package.json
  pnpm-lock.yaml
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/feature, release-note, approved

#693 fix: the problem of incorrect hint of opening developer option
  src/components/Tools/Logo.vue
Labels: kind/bug, release-note-none, approved, lgtm

#688 refactor: use generateName instead of uuid to generate metadata.name
  package.json
  pnpm-lock.yaml
  src/composables/use-setting-form.ts
  src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/system/roles/components/RoleEditingModal.vue
  src/modules/system/roles/composables/use-role.ts
  src/modules/system/users/Login.vue
  src/utils/id.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#695 feat: add delete attachment group and policy support
  packages/components/src/components/button/Button.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/composables/use-attachment-group.ts
  src/modules/contents/attachments/composables/use-attachment-policy.ts
Labels: kind/feature, release-note, approved, lgtm

#696 refactor: save and publishing logic for post and single page
  package.json
  pnpm-lock.yaml
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#697 chore: release 2.0.0-beta.2
  package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#698 feat: post editor page supports the parameter of returnToView
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
Labels: kind/feature, release-note, approved, lgtm

#701 perf: adding the necessary validation to the forms
  src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/comments/components/ReplyCreationModal.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/system/roles/components/RoleEditingModal.vue
  src/modules/system/users/components/UserEditingModal.vue
  src/modules/system/users/components/UserPasswordChangeModal.vue
  src/views/system/Setup.vue
Labels: release-note, approved, lgtm, kind/improvement

#700 perf: set maximum width for entity-field to prevent text overflow
  packages/components/src/components/entity/Entity.vue
  packages/components/src/components/entity/EntityField.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/pages/SinglePageList.vue
Labels: release-note, approved, lgtm, kind/improvement

#702 perf: improve the list filter style and support clear all
  src/components/filter/FilterCleanButton.vue
  src/components/filter/FilterTag.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/system/plugins/PluginList.vue
Labels: release-note, approved, lgtm, kind/improvement

#699 refactor: managing logged-in user states with pinia
  src/layouts/BasicLayout.vue
  src/main.ts
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/system/users/Login.vue
  src/modules/system/users/UserList.vue
  src/modules/system/users/components/UserPasswordChangeModal.vue
  src/router/guards/auth-check.ts
  src/stores/user.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#705 Change package version to 1.5.6
  package.json
Labels: release-note-none, approved, lgtm

#703 refactor: add loading states for data list
  packages/components/src/components.ts
  packages/components/src/components/loading/Loading.vue
  packages/components/src/components/loading/index.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/tags/TagList.vue
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/plugins/PluginSetting.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
  src/modules/system/users/UserList.vue
  src/setup/setupStyles.ts
  src/styles/index.css
Labels: release-note, approved, lgtm, kind/improvement

#706 feat: add query attachments by ungrouped parameter support
  package.json
  pnpm-lock.yaml
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/feature, release-note, approved, lgtm

#707 chore: bump dependencies
  package.json
  packages/components/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: release-note-none, approved, lgtm, kind/improvement

#708 fix: splash screen issue caused by refreshing the list at regular intervals
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/system/plugins/PluginList.vue
Labels: kind/bug, release-note-none, approved, lgtm

#709 perf: back to post list when post is first created
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#710 chore: release 2.0.0-rc.1
  package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#714 chore: add @Aanko to reviewer list
  OWNERS
Labels: release-note-none, approved, lgtm, kind/improvement

#719 chore: bump @halo-dev/richtext-editor version
  package.json
  pnpm-lock.yaml
  src/components/editor/DefaultEditor.vue
Labels: release-note, approved, lgtm, kind/improvement

#711 chore: bump @halo-dev/api-client for reload theme api
  package.json
  pnpm-lock.yaml
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
Labels: release-note-none, approved, kind/api-change, lgtm

#723 perf: unify the copywriting style of confirms
  src/layouts/BasicLayout.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/system/plugins/composables/use-plugin.ts
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
Labels: release-note, approved, lgtm, kind/improvement

#721 feat: add support for automatic label color calculation for post tags
  src/modules/contents/posts/tags/components/PostTag.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/views/system/setup-data/tag.json
Labels: kind/feature, release-note, approved, lgtm

#722 chore: bump @halo-dev/richtext-editor to support more features
  package.json
  pnpm-lock.yaml
  src/components/editor/DefaultEditor.vue
Labels: release-note, approved, lgtm, kind/improvement

#724 perf: formkit post input type only queries the available
  src/formkit/inputs/post-select.ts
  src/formkit/inputs/singlePage-select.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#725 fix: the issue that the menu is not updated after the menu item is deleted
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#726 perf: remove the list of users under role details
  src/modules/system/roles/RoleDetail.vue
  src/modules/system/roles/RoleList.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#720 feat: post list supports displaying the pinned status
  src/modules/contents/posts/PostList.vue
Labels: kind/feature, release-note, approved, lgtm

#713 feat: set the approvedTime field during approve
  package.json
  pnpm-lock.yaml
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
Labels: release-note, approved, lgtm, kind/improvement

#716 fix: issue of uploading attachments to ungrouped group
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
Labels: kind/bug, release-note, approved, lgtm

#717 fix: the issue that role edit form cannot be submitted in the permission tab
  src/modules/system/roles/components/RoleEditingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#712 perf: allow clicking on the link address of the data list
  packages/components/src/components/entity/EntityField.vue
  src/components/editor/DefaultEditor.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/components/CategoryListItem.vue
  src/modules/contents/posts/tags/TagList.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
  src/modules/interface/themes/ThemeDetail.vue
Labels: release-note, approved, lgtm, kind/improvement

#718 fix: the issue that post publishTime cannot be set and displayed back
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/utils/__tests__/date.spec.ts
  src/utils/date.ts
Labels: kind/bug, release-note, approved, lgtm

#729 refactor: simplify references in Attachment
  package.json
  pnpm-lock.yaml
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#730 refactor: simplify MenuItem with targetRef instead of multi refs
  package.json
  pnpm-lock.yaml
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#733 refactor: remove the option to make the post internally accessible to members
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#732 feat: add global request error toast
  src/utils/api-client.ts
Labels: kind/feature, release-note, approved, lgtm

#731 feat: post editing pages support caching of content to the browser
  package.json
  pnpm-lock.yaml
  src/composables/use-content-cache.ts
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
Labels: kind/feature, release-note, approved, lgtm

#735 feat: add exception pages
  src/views/exceptions/Forbidden.vue
  src/views/exceptions/NotFound.vue
  src/views/exceptions/components/Exception.vue
Labels: kind/feature, release-note, approved, lgtm

#734 Fix rich editor tooltip typo for insert attachments button
  src/components/editor/DefaultEditor.vue
Labels: kind/bug, release-note-none, approved, lgtm

#737 refactor: plugin author field
  package.json
  pnpm-lock.yaml
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/components/PluginListItem.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#740 perf: hide toast on setup page
  src/main.ts
  src/stores/system-states.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#739 perf: refine setup data and logic of post publish
  src/views/system/Setup.vue
  src/views/system/setup-data/menu-items.json
  src/views/system/setup-data/post.json
  src/views/system/setup-data/singlePage.json
Labels: release-note-none, approved, lgtm, kind/improvement

#738 refactor: plugin extension points of console plugin
  packages/shared/src/core/plugins.ts
  packages/shared/src/states/attachment-selector.ts
  packages/shared/src/states/pages.ts
  packages/shared/src/types/plugin.ts
  src/composables/usePlugins.ts
  src/main.ts
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/attachments/module.ts
  src/modules/contents/comments/module.ts
  src/modules/contents/pages/FunctionalPageList.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/module.ts
  src/modules/dashboard/module.ts
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/module.ts
  src/modules/system/roles/module.ts
  src/modules/system/settings/module.ts
  src/modules/system/users/module.ts
  src/stores/plugin.ts
Labels: release-note-none, approved, lgtm, kind/improvement
