Repository halo-dev/console, pull requests merged in 2022-05, with the labels that each got.

#558 fix: routing loop entry after reinstallation
  src/router/guard/permissionGuard.js
Labels: kind/bug, approved, lgtm

#561 docs: update README.md for issue feedback
  README.md
Labels: approved, kind/documentation, lgtm

#562 chore: bump @halo-dev/editor to resolve duplicate rendering issue
  package.json
  pnpm-lock.yaml
Labels: kind/bug, approved, lgtm

#564 perf: optimize the layout of some forms on mobile
  src/components/Category/CategoryCreateModal.vue
  src/components/Post/PostSettingModal.vue
  src/views/sheet/components/SheetSettingModal.vue
  src/views/sheet/independent/components/PhotoFormModal.vue
Labels: kind/feature, approved, lgtm

#566 release: 1.5.3
  package.json
Labels: approved, lgtm

#569 chore: add pull request template
  .github/pull_request_template.md
Labels: release-note-none, approved, kind/documentation, lgtm

#568 refactor: remove encodeURI handling of attachment paths.
  src/components/Attachment/AttachmentDetailModal.vue
  src/components/Attachment/AttachmentSelectModal.vue
  src/components/Editor/MarkdownEditor.vue
  src/components/Input/AttachmentInput.vue
  src/components/Post/PostSettingModal.vue
  src/views/attachment/AttachmentList.vue
  src/views/sheet/components/SheetSettingModal.vue
  src/views/sheet/independent/PhotoList.vue
  src/views/sheet/independent/components/PhotoFormModal.vue
Labels: kind/bug, release-note-none, approved, lgtm

#571 fix typo: profile email message typo.
  src/views/user/Profile.vue
Labels: release-note-none, approved, lgtm

#576 Replace zh-cmn-Hans with cmn-Hans
  public/index.html
Labels: kind/cleanup, release-note, approved, lgtm, kind/deprecation

#577 fix: ui issue caused by too long parent category selection list in new category
  src/components/Category/CategorySelectTree.vue
Labels: release-note, approved, lgtm
