Repository halo-dev/console, pull requests merged in 2022-08, with the labels that each got.

#592 feat: add support for theme management
  package.json
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/composables/use-theme.ts
Labels: kind/feature, release-note-none, approved, lgtm

#574 feat: links and link groups support drag and drop sorting
  package.json
  pnpm-lock.yaml
  src/views/sheet/components/LinkCreateModal.vue
  src/views/sheet/independent/LinkList.vue
Labels: kind/feature, release-note, approved, lgtm

#594 feat: add theme install support
  package.json
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/modules/interface/themes/components/ThemeInstallModal.vue
  src/modules/interface/themes/components/ThemeListModal.vue
Labels: kind/feature, release-note-none, approved, lgtm

#596 feat: add theme uninstall support
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  src/modules/interface/themes/components/ThemeListModal.vue
Labels: kind/feature, release-note-none, approved, lgtm

#597 typo: power to powered
  src/components/GlobalFooter/GlobalFooter.vue
Labels: release-note-none, approved, kind/documentation, lgtm

#598 chore: update caniuse-lite for browserslist
  pnpm-lock.yaml
Labels: release-note-none, approved, lgtm

#599 feat: post basic management capability
  package.json
  packages/components/src/components/tag/Tag.vue
  packages/components/src/icons/icons.ts
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/constants/labels.ts
  src/formkit/theme.ts
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/categories/components/CategoryListItem.vue
  src/modules/contents/posts/categories/components/__tests__/CategoryEditingModal.spec.ts
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/categories/utils/index.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/components/__tests__/PostSettingModal.spec.ts
  src/modules/contents/posts/posts-mock.ts
  src/modules/contents/posts/tags/TagList.vue
  src/modules/contents/posts/tags/components/PostTag.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/dashboard/widgets/RecentPublishedWidget.vue
  src/utils/__tests__/date.spec.ts
  src/utils/date.ts
Labels: kind/feature, release-note-none, approved, lgtm
