Repository halo-dev/console, pull requests merged in 2022-10, with the labels that each got.

#634 refactor: rename admin to console
  .changeset/pre.json
  index.html
  package.json
  packages/components/package.json
  packages/shared/package.json
  packages/shared/vite.config.ts
  pnpm-lock.yaml
  src/build/library-external.ts
  src/composables/usePlugins.ts
  src/main.ts
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/attachments/module.ts
  src/modules/contents/comments/module.ts
  src/modules/contents/pages/FunctionalPageList.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/module.ts
  src/modules/dashboard/module.ts
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/layouts/PluginLayout.vue
  src/modules/system/plugins/module.ts
  src/modules/system/roles/module.ts
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
  src/modules/system/settings/module.ts
  src/modules/system/users/layouts/UserProfileLayout.vue
  src/modules/system/users/module.ts
  src/router/menus.config.ts
  src/router/routes.config.ts
  src/setup/setupStyles.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#635 chore: add pull request template and remove auto assign config file
  .github/auto_assign.yml
  .github/pull_request_template.md
Labels: release-note-none, approved, kind/documentation, lgtm

#631 perf: batch add to photos in order of image selection
  src/views/sheet/independent/PhotoList.vue
Labels: release-note, approved, lgtm, kind/improvement

#636 refactor: logic of user login
  packages/shared/src/layouts/BasicLayout.vue
  src/components/global-search/GlobalSearchModal.vue
  src/main.ts
  src/modules/system/users/Login.vue
  src/router/guards/auth-check.ts
  src/router/guards/check-states.ts
  src/router/index.ts
  src/utils/api-client.ts
Labels: release-note, approved, lgtm, kind/improvement

#640 release: 1.5.5
  package.json
Labels: release-note-none, approved, lgtm

#639 release: 1.6.0
  package.json
Labels: release-note-none, approved, lgtm

#641 Add Makefile for convenient operations
  Makefile
Labels: kind/feature, release-note-none, approved, lgtm, area/console

#642 fix: `build:packages` script not running on Windows
  package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#644 feat: add toast component
  packages/components/src/components.ts
  packages/components/src/components/toast/Toast.story.vue
  packages/components/src/components/toast/Toast.vue
  packages/components/src/components/toast/index.ts
  packages/components/src/components/toast/interface.ts
  packages/components/src/components/toast/toast-manager.ts
Labels: kind/feature, release-note, approved, lgtm

#649 perf: refine the fallback of the avatar component
  packages/components/src/components/avatar/Avatar.story.vue
  packages/components/src/components/avatar/Avatar.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/system/users/layouts/UserProfileLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#646 refactor: api of dialog component
  packages/components/src/components/dialog/Dialog.story.vue
  packages/components/src/components/dialog/DialogProvider.vue
  packages/components/src/components/dialog/dialog-manager.ts
  packages/components/src/components/dialog/index.ts
  packages/components/src/components/dialog/interface.ts
  packages/components/src/components/dialog/use-dialog.ts
  packages/shared/src/layouts/BasicLayout.vue
  src/App.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/system/plugins/components/PluginInstallModal.vue
  src/modules/system/plugins/composables/use-plugin.ts
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
Labels: release-note, approved, kind/api-change, lgtm, kind/improvement

#645 feat: add operation exception toasts for loading plugin resources and login
  packages/components/src/components/dialog/Dialog.story.vue
  src/main.ts
  src/modules/system/users/Login.vue
Labels: kind/feature, release-note, approved, lgtm

#643 feat: add some formkit custom input for the system core extensions
  docs/custom-formkit-input/README.md
  src/formkit/formkit.config.ts
  src/formkit/inputs/category-checkbox.ts
  src/formkit/inputs/category-select.ts
  src/formkit/inputs/form.ts
  src/formkit/inputs/menu-checkbox.ts
  src/formkit/inputs/menu-item-select.ts
  src/formkit/inputs/menu-radio.ts
  src/formkit/inputs/post-select.ts
  src/formkit/inputs/singlePage-select.ts
  src/formkit/inputs/tag-checkbox.ts
  src/formkit/inputs/tag-select.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: kind/feature, release-note, approved, lgtm

#651 refactor: router and menu generation
  docs/routes-generation/README.md
  env.d.ts
  package.json
  packages/components/src/components/menu/__tests__/RoutesMenu.spec.tsx
  packages/components/src/components/menu/index.ts
  packages/components/src/components/menu/interface.ts
  packages/shared/env.d.ts
  packages/shared/package.json
  packages/shared/postcss.config.js
  packages/shared/src/assets/logo.svg
  packages/shared/src/index.ts
  packages/shared/src/layouts/__tests__/BasicLayout.spec.ts
  packages/shared/src/layouts/index.ts
  packages/shared/src/types/menus.ts
  packages/shared/src/types/plugin.ts
  packages/shared/tailwind.config.js
  packages/shared/vite.config.ts
  pnpm-lock.yaml
  src/App.vue
  src/components/global-search/GlobalSearchModal.vue
  src/components/menu/RoutesMenu.tsx
  src/layouts/BasicLayout.vue
  src/layouts/BlankLayout.vue
  src/main.ts
  src/modules/contents/attachments/module.ts
  src/modules/contents/comments/module.ts
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/module.ts
  src/modules/dashboard/module.ts
  src/modules/index.ts
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/layouts/PluginLayout.vue
  src/modules/system/plugins/module.ts
  src/modules/system/roles/module.ts
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
  src/modules/system/settings/module.ts
  src/modules/system/users/layouts/UserProfileLayout.vue
  src/modules/system/users/module.ts
  src/router/menus.config.ts
  src/router/routes.config.ts
  src/setup/setupStyles.ts
Labels: release-note, approved, kind/api-change, lgtm, kind/improvement

#652 chore: bump @halo-dev/api-client for post stats
  package.json
  pnpm-lock.yaml
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/dashboard/widgets/RecentPublishedWidget.vue
  src/modules/dashboard/widgets/ViewsStatsWidget.vue
Labels: kind/bug, release-note, approved, kind/api-change, lgtm

#654 chore: bump packages version
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#653 feat: add upgrade theme support
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/components/ThemeUploadModal.vue
Labels: kind/feature, release-note, approved, lgtm

#656 feat: add a refresh button to the data list
  packages/components/src/icons/icons.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/system/plugins/PluginList.vue
Labels: kind/feature, release-note, approved, lgtm

#657 refactor: load the theme and plugin logos using the avatar component
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#658 chore: remove the step to run unit tests and typecheck before git commit
  .husky/pre-commit
Labels: release-note-none, approved, lgtm, kind/improvement

#659 docs: update repobeats analytics images source for readme file
  README.md
Labels: release-note-none, approved, kind/documentation, lgtm

#660 feat: add preview theme support
  src/components/preview/UrlPreviewModal.vue
  src/modules/interface/themes/components/ThemeListModal.vue
Labels: kind/feature, release-note, approved, lgtm

#664 refactor: load the logo as an inline svg
  src/layouts/BasicLayout.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/components/ThemeUploadModal.vue
  src/modules/system/users/Login.vue
  src/views/system/Setup.vue
  vite.config.ts
  vitest.config.ts
Labels: release-note, approved, lgtm, kind/improvement

#663 feat: add upgrade plugin support
  package.json
  pnpm-lock.yaml
  src/modules/system/plugins/PluginList.vue
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/plugins/components/PluginUploadModal.vue
Labels: kind/feature, release-note, approved, lgtm

#666 refactor: upload component changed from filepond to uppy
  package.json
  pnpm-lock.yaml
  src/components/upload/FilePondUpload.vue
  src/components/upload/UppyUpload.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/interface/themes/components/ThemeUploadModal.vue
  src/modules/system/plugins/components/PluginUploadModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#667 chore: bump dependencies
  package.json
  packages/components/package.json
  packages/components/src/components/menu/__tests__/Menu.spec.tsx
  packages/shared/package.json
  pnpm-lock.yaml
Labels: release-note-none, approved, lgtm, kind/improvement

#668 fix: logo cannot be displayed after the build
  src/assets/logo.svg
Labels: kind/bug, release-note-none, approved, lgtm

#669 chore: release 2.0.0-alpha.3
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm

#673 perf: improve the layout and style of forms
  src/formkit/theme.ts
  src/modules/contents/comments/components/ReplyCreationModal.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/system/plugins/PluginSetting.vue
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/users/layouts/UserProfileLayout.vue
Labels: release-note, approved, lgtm, kind/improvement
