Repository halo-dev/console, pull requests merged in 2022-12, with the labels that each got.

#741 chore: release 2.0.0
  package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#742 perf: add autofocus to login username input
  src/components/login/LoginForm.vue
Labels: release-note, approved, lgtm, kind/improvement

#744 feat: api client requests support configuring the mute parameter to hide exception toast
  env.d.ts
  src/composables/use-setting-form.ts
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/system/plugins/composables/use-plugin.ts
  src/stores/system-states.ts
  src/stores/theme.ts
  src/utils/api-client.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#743 fix: the issue that custom link type menu items cannot be saved normally
  src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#747 perf: improve the text of the upgrade theme button
  src/modules/interface/themes/ThemeDetail.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#746 fix: ui is not updated after the theme is activated in the production
  src/stores/theme.ts
Labels: kind/bug, release-note, approved, lgtm

#748 perf: optimize the issue of animation when switching setting tabs
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginSetting.vue
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#750 fix: plugin failed to get settings when plugin is stopped
  src/modules/system/plugins/layouts/PluginLayout.vue
Labels: kind/bug, release-note, approved, lgtm

#749 feat: refining the logic of user roles
  src/constants/constants.ts
  src/constants/labels.ts
  src/modules/system/roles/RoleDetail.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/roles/composables/use-role.ts
Labels: kind/bug, release-note, approved, lgtm

#758 docs: update readme for Halo 2.0
  README.md
Labels: release-note-none, approved, kind/documentation, lgtm

#745 perf: add tooltip for some icon buttons
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/users/components/UserEditingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#763 fix: cannot save post when the publishTime is blank
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#762 refactor: remove form-related components
  packages/components/src/components.ts
  packages/components/src/components/card/Card.story.vue
  packages/components/src/components/checkbox/CheckBox.story.vue
  packages/components/src/components/checkbox/CheckBox.vue
  packages/components/src/components/checkbox/CheckBoxGroup.vue
  packages/components/src/components/checkbox/__tests__/CheckBox.spec.ts
  packages/components/src/components/checkbox/__tests__/CheckBoxGroup.spec.ts
  packages/components/src/components/checkbox/__tests__/__snapshots__/CheckBox.spec.ts.snap
  packages/components/src/components/checkbox/__tests__/__snapshots__/CheckBoxGroup.spec.ts.snap
  packages/components/src/components/checkbox/index.ts
  packages/components/src/components/entity/EntityField.vue
  packages/components/src/components/input/Input.story.vue
  packages/components/src/components/input/Input.vue
  packages/components/src/components/input/__tests__/Input.spec.ts
  packages/components/src/components/input/__tests__/__snapshots__/Input.spec.ts.snap
  packages/components/src/components/input/index.ts
  packages/components/src/components/input/interface.ts
  packages/components/src/components/radio/Radio.story.vue
  packages/components/src/components/radio/Radio.vue
  packages/components/src/components/radio/RadioGroup.vue
  packages/components/src/components/radio/__tests__/Radio.spec.ts
  packages/components/src/components/radio/__tests__/RadioGroup.spec.ts
  packages/components/src/components/radio/__tests__/__snapshots__/Radio.spec.ts.snap
  packages/components/src/components/radio/__tests__/__snapshots__/RadioGroup.spec.ts.snap
  packages/components/src/components/radio/index.ts
  packages/components/src/components/select/Option.vue
  packages/components/src/components/select/Select.story.vue
  packages/components/src/components/select/Select.vue
  packages/components/src/components/select/__tests__/Select.spec.ts
  packages/components/src/components/select/__tests__/__snapshots__/Select.spec.ts.snap
  packages/components/src/components/select/index.ts
  packages/components/src/components/select/interface.ts
  packages/components/src/components/space/Space.story.vue
  packages/components/src/components/textarea/Textarea.story.vue
  packages/components/src/components/textarea/Textarea.vue
  packages/components/src/components/textarea/__tests__/Textarea.spec.ts
  packages/components/src/components/textarea/__tests__/__snapshots__/Textarea.spec.ts.snap
  packages/components/src/components/textarea/index.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#767 fix: the global search keyboard event is not removed when the component is unmounted
  src/layouts/BasicLayout.vue
Labels: kind/bug, release-note-none, approved, lgtm

#768 chore: use lint-staged to improve dx
  .husky/pre-commit
  .prettierignore
  package.json
  pnpm-lock.yaml
Labels: release-note-none, approved, lgtm, kind/improvement

#769 perf: improve the prompt for upload failure of the upload component
  src/components/upload/UppyUpload.vue
  src/utils/api-client.ts
Labels: release-note, approved, lgtm, kind/improvement

#775 docs: update github workflow badge
  README.md
Labels: release-note-none, approved, lgtm, kind/improvement

#778 chore: bump version for Halo 2.0.2
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#780 perf: optimize the operation button style of the entity component
  packages/components/src/components/entity/Entity.vue
Labels: release-note, approved, lgtm, kind/improvement

#779 perf: merge plugin uninstallation options button
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/plugins/composables/use-plugin.ts
Labels: release-note, approved, lgtm, kind/improvement

#777 feat: add support for resetting configmap of plugin and theme
  package.json
  pnpm-lock.yaml
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/components/ThemeListItem.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/system/plugins/components/PluginListItem.vue
Labels: kind/feature, release-note, approved, lgtm

#782 fix: the flickering issue of tooltip
  src/App.vue
Labels: release-note, approved, lgtm, kind/improvement

#785 perf: add more operation feedback prompt
  src/composables/use-setting-form.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyCreationModal.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/contents/pages/DeletedSinglePageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/components/components/ThemeListItem.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/system/plugins/composables/use-plugin.ts
  src/modules/system/roles/RoleList.vue
  src/modules/system/roles/composables/use-role.ts
  src/modules/system/users/UserList.vue
  src/modules/system/users/components/UserEditingModal.vue
  src/views/system/Setup.vue
Labels: release-note, approved, lgtm, kind/improvement

#787 fix: system settings form could not be loaded
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
Labels: kind/bug, release-note, approved, lgtm

#792 perf: remove permalink of deleted single page
  src/modules/contents/pages/DeletedSinglePageList.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#781 feat: add editor extension point
  docs/extension-points/editor.md
  packages/shared/src/index.ts
  packages/shared/src/states/editor.ts
  packages/shared/src/types/plugin.ts
  src/components/editor/DefaultEditor.vue
  src/composables/use-editor-extension-points.ts
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
Labels: kind/feature, release-note, approved, lgtm

#790 fix: activated theme not loaded after initialization
  src/views/system/Setup.vue
Labels: kind/bug, release-note, approved, lgtm

#788 feat: add support for setting console's favicon
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/mstile-150x150.png
  public/site.webmanifest
  src/App.vue
  src/main.ts
  src/modules/system/settings/SystemSetting.vue
  src/stores/system-configmap.ts
Labels: kind/feature, release-note, approved, lgtm

#794 Differentiate the title of adding and editing menu and menu item
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#789 perf: improve the layout of the post list
  packages/components/src/components/entity/EntityField.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
Labels: release-note, approved, lgtm, kind/improvement

#791 refactor: add validation for post and singlePage settings form
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#797 perf: automatic refresh of the list of users and roles
  src/modules/system/roles/RoleList.vue
  src/modules/system/roles/composables/use-role.ts
  src/modules/system/users/UserList.vue
Labels: release-note, approved, lgtm, kind/improvement

#795 refactor: layouts of role editing form
  src/modules/system/roles/components/RoleEditingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#798 perf: asynchronously load the emoji data of the comment reply component
  src/modules/contents/comments/components/ReplyCreationModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#784 refactor: attachment upload component
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
Labels: approved, lgtm, kind/improvement

#799 refactor: remove the ability to edit user using yaml
  package.json
  pnpm-lock.yaml
  src/modules/system/users/components/UserEditingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#800 perf: asynchronously load the default editor
  src/composables/use-editor-extension-points.ts
Labels: release-note, approved, lgtm, kind/improvement

#770 feat: add AnnotationsForm Component to edit extension annotations
  package.json
  pnpm-lock.yaml
  src/components/form/AnnotationsForm.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/utils/api-client.ts
Labels: kind/feature, release-note, approved, lgtm

#801 feat: add annotations form for more extension
  src/components/form/AnnotationsForm.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/system/users/components/UserEditingModal.vue
Labels: kind/feature, release-note-none, approved, lgtm

#802 chore: release 2.1.0-rc.1
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#796 fix: logged-in users cannot access the profile page
  package.json
  pnpm-lock.yaml
  src/layouts/BasicLayout.vue
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/system/users/components/UserEditingModal.vue
  src/modules/system/users/layouts/UserProfileLayout.vue
Labels: kind/bug, release-note, approved, lgtm

#807 fix: saving an post causes the publish time to be lost
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#804 fix: login in safari browser has no effect
  src/modules/system/users/Login.vue
Labels: kind/bug, release-note, approved, lgtm

#809 fix: saving an post causes the publish time to be lost
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
Labels: kind/bug, release-note, approved, lgtm

#806 fix: preferred-editor annotation is not set when editing old posts
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, release-note-none, approved, lgtm

#803 refactor: editor provider switching
  src/assets/logo.png
  src/components/dropdown-selector/EditorProviderSelector.vue
  src/composables/use-editor-extension-points.ts
  src/main.ts
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
  src/stores/plugin.ts
Labels: release-note, approved, lgtm, kind/improvement

#805 feat: add target attribute setting for menu item
  package.json
  pnpm-lock.yaml
  src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: kind/feature, release-note, approved, lgtm

#810 Bump Console to 2.0.3
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#811 chore: release 2.1.0
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#812 fix: remove login form icon, fix icon lose warning
  src/components/login/LoginForm.vue
Labels: release-note-none, approved, lgtm
