Repository halo-dev/console, pull requests merged in 2022-03, with the labels that each got.

#473 chore: modify the cdn address of the less dependency
  src/components/SettingDrawer/setting.js
Labels: dependencies

#474 fix: attachment list can't to display images with space path
  src/components/Attachment/AttachmentSelectModal.vue
  src/views/attachment/AttachmentList.vue
Labels: bug

#475 refactor: post management
  src/components/Category/CategorySelectTree.vue
  src/components/Category/CategoryTree.vue
  src/components/Category/CategoryTreeNode.vue
  src/components/Post/PostListView.vue
  src/components/Post/PostSettingModal.vue
  src/components/Post/RecyclePostModal.vue
  src/components/Tag/TagSelect.vue
  src/core/constant.js
  src/views/post/CategoryList.vue
  src/views/post/PostEdit.vue
  src/views/post/PostList.vue
Labels: enhancement

#478 chore: next major version base project
  .eslintrc.cjs
  .gitignore
  .vscode/extensions.json
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/example.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/tsconfig.json
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  env.d.ts
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  src/App.vue
  src/assets/base.css
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/__tests__/HelloWorld.spec.ts
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.ts
  src/router/index.ts
  src/stores/counter.ts
  src/views/AboutView.vue
  src/views/HomeView.vue
  tsconfig.app.json
  tsconfig.json
  tsconfig.vite-config.json
  tsconfig.vitest.json
  vite.config.ts
Labels: enhancement

#479 chore: add pre commit hook
  .eslintrc.cjs
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/components/TheWelcome.vue
  src/views/HomeView.vue
Labels: enhancement

#480 feat: comment management page adds a list of comments to the journal
  src/components/Comment/TargetCommentTreeNode.vue
  src/styles/global.less
  src/views/comment/CommentList.vue
  src/views/comment/components/CommentTab.vue
  src/views/sheet/independent/JournalList.vue
Labels: enhancement

#489 feat: support new categories in post settings
  src/components/Category/CategoryCreateModal.vue
  src/components/Post/PostSettingModal.vue
Labels: enhancement

#490 perf: update localStorage namespace
  src/config/defaultSettings.js
Labels: enhancement

#492 fix: the problem of incorrect hint of opening developer option
  package.json
  pnpm-lock.yaml
  src/components/Tools/Logo.vue
Labels: bug

#493 perf: optimize the experience of collapsing the menu
  src/App.vue
  src/components/GlobalHeader/GlobalHeader.vue
  src/components/SettingDrawer/SettingDrawer.vue
  src/components/Tools/Logo.vue
  src/layouts/BasicLayout.vue
  src/store/getters.js
  src/store/modules/app.js
Labels: enhancement

#494 chore: cleanup unnecessary files
  .husky/pre-commit
  src/App.vue
  src/assets/base.css
  src/assets/logo.svg
  src/components/.gitkeep
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/__tests__/HelloWorld.spec.ts
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/router/index.ts
  src/views/AboutView.vue
  src/views/HomeView.vue
  src/views/__tests__/HomeView.spec.ts
Labels: enhancement

#495 perf: optimize the logic for determining whether to initialize
  src/router/guard/permissionGuard.js
  src/store/getters.js
  src/store/modules/app.js
  src/store/modules/option.js
  src/views/system/Installation.vue
  src/views/user/Login.vue
Labels: bug

#496 fix: the attachment list image is not updated after paging
  src/components/Attachment/AttachmentSelectModal.vue
  src/views/attachment/AttachmentList.vue
  src/views/sheet/independent/PhotoList.vue
Labels: bug

#499 feat: support to modify menu team name
  src/views/interface/MenuList.vue
Labels: enhancement

#504 chore: configure tailwind css
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/main.ts
  src/styles/tailwind.css
  src/views/HomeView.vue
  tailwind.config.js
Labels: enhancement, dependencies

#505 feat: update avatar support to modify the avatar link
  src/components/Input/AttachmentInput.vue
  src/views/user/Profile.vue
Labels: enhancement

#506 refactor: journal editing using the markdown editor
  package.json
  pnpm-lock.yaml
  src/components/Editor/MarkdownEditor.vue
  src/core/constant.js
  src/views/dashboard/components/JournalPublishCard.vue
  src/views/sheet/independent/JournalList.vue
Labels: enhancement

#510 chore: add histoire support
  .eslintrc.cjs
  .gitignore
  histoire.config.ts
  package.json
  pnpm-lock.yaml
  src/components/base/button/Button.story.vue
  src/components/base/button/Button.vue
  src/components/base/button/index.ts
  src/components/base/button/interface.ts
Labels: enhancement

#514 feat: theme visual settings page add back button
  src/views/interface/ThemeVisualSetting.vue
  src/views/interface/components/ThemeSettingForm.vue
Labels: enhancement

#515 feat: add button component
  package.json
  pnpm-lock.yaml
  src/components/base/button/Button.story.vue
  src/components/base/button/Button.vue
  src/components/base/button/__tests__/Button.spec.ts
Labels: enhancement

#516 chore: add unit test github action steps
  .github/workflows/main.yml
Labels: enhancement

#517 feat: auditing comments modal support click into the comment management
  src/components/Comment/CommentListView.vue
  src/components/Comment/TargetCommentListModal.vue
  src/components/Comment/TargetCommentTreeNode.vue
  src/components/Tools/HeaderComment.vue
  src/components/Tools/HeaderCommentTab.vue
  src/components/Tools/index.js
  src/styles/global.less
  src/views/comment/CommentList.vue
  src/views/comment/components/CommentTab.vue
Labels: enhancement

#520 Fix the problem of failure to create menu based on internal preset links
  src/views/interface/components/MenuInternalLinkSelector.vue
Labels: approved, lgtm

#524 fix: wrong path to referenced image
  src/components/SettingDrawer/SettingDrawer.vue
Labels: kind/bug, approved, lgtm

#525 fix: the mode.topPriority involving computed is not initialized
  src/components/Post/PostSettingModal.vue
Labels: kind/bug, approved, lgtm

#526 fix: error message of sending email test
  src/views/system/optiontabs/SmtpTab.vue
Labels: kind/bug, approved, lgtm

#529 chore: bump @halo-dev/editor to resolve Chinese IME suggestion list obscures inputted text
  package.json
  pnpm-lock.yaml
Labels: kind/bug, approved, lgtm

#530 fix: initial value of topPriority in post settings
  src/components/Post/PostSettingModal.vue
Labels: kind/bug, approved, lgtm

#527 fix: deep sub-categories not showing has password status
  src/views/post/CategoryList.vue
Labels: kind/bug, approved, lgtm

#531 release: 1.5.1
  package.json
Labels: approved, lgtm
