Repository halo-dev/console, pull requests merged in 2022-09, with the labels that each got.

#601 fix: failed to set journal page size option
  src/views/sheet/independent/JournalList.vue
  src/views/sheet/independent/LinkList.vue
  src/views/sheet/independent/PhotoList.vue
Labels: kind/bug, release-note-none, approved, lgtm

#600 feat: add attachment management support
  package.json
  packages/components/src/components/modal/Modal.vue
  packages/shared/package.json
  packages/shared/src/composables/use-setting-form.ts
  packages/shared/src/index.ts
  packages/shared/src/states/attachment-selector.ts
  packages/shared/src/types/plugin.ts
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/components/image/LazyImage.vue
  src/components/upload/FilePondUpload.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentAliOSSStrategyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/AttachmentFileTypeIcon.vue
  src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentLocalStrategyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentSelectModal.vue
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/attachments/components/AttachmentStrategiesModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment-group.ts
  src/modules/contents/attachments/composables/use-attachment-policy.ts
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/attachments/module.ts
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/system/users/UserList.vue
  src/utils/image.ts
  tsconfig.app.json
  vite.config.ts
Labels: kind/feature, release-note-none, approved, lgtm

#605 refactor: method parameters of api client
  package.json
  packages/shared/package.json
  packages/shared/src/composables/use-setting-form.ts
  packages/shared/src/layouts/PluginLayout.vue
  pnpm-lock.yaml
  src/main.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/posts/PostEditor.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/TagList.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/menus/utils/__tests__/__snapshots__/index.spec.ts.snap
  src/modules/interface/menus/utils/__tests__/index.spec.ts
  src/modules/interface/menus/utils/index.ts
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/plugins/components/PluginInstallModal.vue
  src/modules/system/plugins/composables/use-plugin.ts
  src/modules/system/roles/RoleDetail.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/roles/composables/use-role.ts
  src/modules/system/users/UserList.vue
  src/modules/system/users/components/UserEditingModal.vue
  src/modules/system/users/components/UserPasswordChangeModal.vue
  src/modules/system/users/layouts/UserProfileLayout.vue
  src/stores/role.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#603 feat: system configmap setting page
  packages/shared/package.json
  packages/shared/src/composables/use-setting-form.ts
  pnpm-lock.yaml
  src/modules/system/settings/CodeInjectSettings.vue
  src/modules/system/settings/CommentSettings.vue
  src/modules/system/settings/GeneralSettings.vue
  src/modules/system/settings/NotificationSettings.vue
  src/modules/system/settings/PostSettings.vue
  src/modules/system/settings/SeoSettings.vue
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/settings/UserSettings.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
  src/modules/system/settings/module.ts
Labels: kind/feature, do-not-merge/hold, release-note-none, approved, lgtm

#604 feat: menu items support setting ref relations
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/TagList.vue
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
Labels: kind/feature, release-note-none, approved, lgtm

#606 feat: single page management
  package.json
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/pages/FunctionalPageList.vue
  src/modules/contents/pages/PageList.vue
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/PostEditor.vue
Labels: kind/feature, release-note-none, approved, lgtm

#608 feat: menu items support setting singlePage ref relations
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  src/modules/interface/menus/components/MenuItemEditingModal.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
Labels: kind/feature, release-note-none, approved, lgtm

#609 feat: add the entity component as a list item
  src/components/entity/Entity.vue
  src/components/entity/EntityField.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/pages/FunctionalPageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/components/CategoryListItem.vue
  src/modules/contents/posts/tags/TagList.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
Labels: kind/feature, release-note-none, approved, lgtm

#610 feat: add buttons that update journal type directly
  src/views/sheet/independent/JournalList.vue
Labels: kind/feature, release-note, approved, lgtm, area/admin

#612 feat: add comment management support
  package.json
  packages/components/src/components/entity/Entity.vue
  packages/components/src/components/entity/EntityField.vue
  packages/components/src/icons/icons.ts
  packages/shared/package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
  src/formkit/utils/focus.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyCreationModal.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  tailwind.config.js
Labels: kind/feature, release-note-none, approved, lgtm

#613 refactor: rename api group for custom api
  package.json
  packages/shared/src/utils/api-client.ts
  pnpm-lock.yaml
Labels: release-note-none, approved, lgtm, kind/improvement

#616 refactor: structure of the setting extension
  package.json
  packages/shared/src/composables/use-setting-form.ts
  packages/shared/src/index.ts
  packages/shared/src/types/formkit.ts
  pnpm-lock.yaml
  src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/system/plugins/PluginSetting.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
  src/modules/system/settings/SystemSetting.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
Labels: release-note-none, approved, kind/api-change, lgtm, kind/improvement

#618 feat: adding random suffix to static resources at build time
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: kind/feature, release-note-none, approved, lgtm

#615 feat: refine post filtering
  package.json
  pnpm-lock.yaml
  src/modules/contents/posts/PostList.vue
Labels: kind/feature, release-note, approved, lgtm

#619 perf: update directly after selecting an avatar
  src/views/user/Profile.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#622 fix: unable to load attachment images in production environment
  src/components/image/LazyImage.vue
Labels: kind/bug, release-note-none, approved, lgtm

#620 feat: add reload theme setting support
  package.json
  pnpm-lock.yaml
  src/modules/interface/themes/ThemeDetail.vue
Labels: kind/feature, release-note-none, approved, lgtm

#621 feat: add deleting theme setting and configMap support
  src/modules/interface/themes/components/ThemeListModal.vue
Labels: kind/feature, release-note, approved, lgtm

#623 feat: add global search support
  package.json
  packages/components/src/components/modal/Modal.vue
  packages/shared/src/layouts/BasicLayout.vue
  pnpm-lock.yaml
  src/App.vue
  src/components/global-search/GlobalSearchModal.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/comments/module.ts
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/module.ts
  src/modules/dashboard/module.ts
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/module.ts
  src/modules/system/roles/module.ts
  src/modules/system/users/module.ts
Labels: kind/feature, release-note, approved, lgtm

#625 feat: singlePage management adds filtering support
  package.json
  pnpm-lock.yaml
  src/modules/contents/pages/SinglePageList.vue
Labels: kind/feature, release-note, approved, lgtm

#627 refactor: update the field for the number of post under categories and tags
  package.json
  pnpm-lock.yaml
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/components/CategoryListItem.vue
  src/modules/contents/posts/tags/TagList.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#626 feat: add display theme location support
  src/modules/interface/themes/ThemeDetail.vue
Labels: kind/feature, release-note, approved, lgtm

#629 feat: add plugin filters support
  package.json
  pnpm-lock.yaml
  src/modules/system/plugins/PluginList.vue
Labels: kind/feature, release-note, approved, lgtm, kind/improvement

#624 feat: support for displaying site content statistics
  package.json
  pnpm-lock.yaml
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/dashboard/widgets/RecentPublishedWidget.vue
  src/modules/dashboard/widgets/ViewsStatsWidget.vue
  src/utils/api-client.ts
Labels: kind/feature, release-note, approved, lgtm

#632 feat: add system setup support
  src/router/guards/check-states.ts
  src/router/index.ts
  src/router/routes.config.ts
  src/stores/system-states.ts
  src/views/system/Setup.vue
  src/views/system/setup-data/category.json
  src/views/system/setup-data/menu-items.json
  src/views/system/setup-data/menu.json
  src/views/system/setup-data/post.json
  src/views/system/setup-data/singlePage.json
  src/views/system/setup-data/tag.json
Labels: kind/feature, release-note-none, approved, lgtm

#628 feat: refine ui permissions
  src/main.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/module.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/contents/comments/module.ts
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/categories/components/CategoryListItem.vue
  src/modules/contents/posts/module.ts
  src/modules/contents/posts/tags/TagList.vue
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/interface/menus/Menus.vue
  src/modules/interface/menus/components/MenuEditingModal.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
  src/utils/permission.ts
Labels: kind/feature, release-note, approved, lgtm, kind/improvement

#630 docs: update readme for Halo 2.0
  README.md
Labels: release-note-none, approved, kind/documentation, lgtm

#633 fix: ui permissions
  src/main.ts
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/tags/components/PostTag.vue
  src/modules/interface/menus/components/MenuItemListItem.vue
  src/modules/interface/menus/components/MenuList.vue
  src/modules/interface/themes/components/ThemeListModal.vue
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
Labels: kind/bug, release-note-none, approved, lgtm
