Repository halo-dev/console, pull requests merged in 2022-04, with the labels that each got.

#535 chore: bump @halo-dev/editor to resolve navigation issue
  package.json
  pnpm-lock.yaml
Labels: kind/bug, approved, lgtm

#536 fix: the icon style in the dashboard statistics is offset
  src/views/dashboard/Dashboard.vue
Labels: kind/bug, approved, lgtm

#538 fix: no category in category management does not show empty tips
  src/views/post/CategoryList.vue
Labels: kind/bug, approved, lgtm

#540 perf: categories in the post settings supports showing whether there is a password or not
  src/components/Category/CategoryTree.vue
Labels: kind/feature, approved, lgtm

#541 perf: categories in the post list filters supports showing whether there is a password or not
  src/components/Category/CategorySelectTree.vue
  src/components/Post/PostListView.vue
Labels: kind/feature, approved, lgtm

#543 refactor: theme color change
  package.json
  pnpm-lock.yaml
  public/color.less
  src/components/SettingDrawer/SettingDrawer.vue
  src/components/SettingDrawer/setting.js
  src/styles/global.less
  src/utils/dynamicTheme.js
  src/webpack/dynamicTheme.js
  vue.config.js
Labels: approved, lgtm

#544 release: 1.5.2
  package.json
Labels: lgtm

#545 fix: abnormal style due to long title of recent posts in the dashboard
  src/views/dashboard/Dashboard.vue
Labels: kind/bug, approved, lgtm

#547 feat: generate gzip products at build time
  package.json
  pnpm-lock.yaml
  vue.config.js
Labels: kind/feature, approved, lgtm

#548 chore: create OWNERS file
  OWNERS
Labels: lgtm

#534 feat: add menu component
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/components/base/menu/Menu.story.vue
  src/components/base/menu/Menu.vue
  src/components/base/menu/MenuItem.vue
  src/components/base/menu/MenuLabel.vue
  src/components/base/menu/RoutesMenu.vue
  src/components/base/menu/__tests__/Menu.spec.tsx
  src/components/base/menu/__tests__/__snapshots__/Menu.spec.tsx.snap
  src/components/base/menu/index.ts
  src/core/icons.ts
  src/router/index.ts
  src/router/menus.config.ts
  src/router/routes.config.ts
  vite.config.ts
Labels: kind/feature, lgtm

#549 perf: add a button to save the settings in the actions area of the theme settings page
  src/views/dashboard/Dashboard.vue
  src/views/interface/ThemeSetting.vue
  src/views/interface/components/ThemeSettingForm.vue
Labels: kind/feature, approved, lgtm

#552 feat: SMTP support configuration starttls
  src/views/system/optiontabs/SmtpTab.vue
Labels: kind/feature, approved, lgtm
