Repository halo-dev/console, pull requests merged in 2022-06, with the labels that each got.

#580 refactor: attachment list layout
  package.json
  pnpm-lock.yaml
  src/components/Attachment/AttachmentSelectModal.vue
  src/styles/global.less
  src/views/attachment/AttachmentList.vue
  src/views/sheet/independent/PhotoList.vue
  tailwind.config.js
Labels: release-note-none, approved, lgtm, kind/improvement

#581 feat: create admin-shared package
  package.json
  packages/shared/.eslintrc.cjs
  packages/shared/env.d.ts
  packages/shared/package.json
  packages/shared/prettier.config.js
  packages/shared/src/components/.gitkeep
  packages/shared/src/index.ts
  packages/shared/src/types/menus.ts
  packages/shared/src/types/plugin.ts
  packages/shared/tsconfig.app.json
  packages/shared/tsconfig.json
  packages/shared/tsconfig.vite-config.json
  packages/shared/tsconfig.vitest.json
  packages/shared/vite.config.ts
  pnpm-lock.yaml
Labels: kind/feature, release-note-none, approved, lgtm

#582 refactor: load admin core as modules
  package.json
  pnpm-lock.yaml
  src/main.ts
  src/modules/contents/attachments/module.ts
  src/modules/contents/comments/module.ts
  src/modules/contents/posts/module.ts
  src/modules/contents/sheets/module.ts
  src/modules/dashboard/module.ts
  src/modules/dashboard/widgets/CommentStatsWidget.vue
  src/modules/dashboard/widgets/JournalPublishWidget.vue
  src/modules/dashboard/widgets/PostStatsWidget.vue
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/dashboard/widgets/RecentLoginWidget.vue
  src/modules/dashboard/widgets/RecentPublishedWidget.vue
  src/modules/dashboard/widgets/UserStatsWidget.vue
  src/modules/dashboard/widgets/ViewsStatsWidget.vue
  src/modules/dashboard/widgets/index.ts
  src/modules/interface/menus/module.ts
  src/modules/interface/themes/module.ts
  src/modules/system/plugins/module.ts
  src/modules/system/roles/module.ts
  src/modules/system/settings/module.ts
  src/modules/system/users/module.ts
  src/router/menus.config.ts
  src/router/routes.config.ts
  src/setup/setupComponents.ts
  src/views/exceptions/NotFound.vue
  vite.config.ts
Labels: kind/feature, release-note-none, approved, lgtm

#554 feat: Add remove EXIF button
  src/store/modules/option.js
  src/views/system/optiontabs/AttachmentTab.vue
Labels: approved, lgtm

#583 feat: plugin management
  package.json
  packages/components/src/components/switch/Switch.vue
  pnpm-lock.yaml
  src/assets/logo-mock/algolia.svg
  src/assets/logo-mock/alibabacloud.svg
  src/assets/logo-mock/amazonaws.svg
  src/assets/logo-mock/elasticsearch.svg
  src/assets/logo-mock/github.svg
  src/assets/logo-mock/halo.png
  src/assets/logo-mock/redis.svg
  src/assets/logo-mock/w3c.svg
  src/assets/logo-mock/wechat.svg
  src/main.ts
  src/modules/contents/sheets/SheetList.vue
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginList.vue
  src/modules/system/plugins/module.ts
  src/modules/system/plugins/plugins-mock.ts
  src/modules/system/plugins/types.d.ts
  src/stores/plugin.ts
  src/utils/api-client.ts
Labels: kind/feature, release-note-none, approved, lgtm
