Repository halo-dev/console, pull requests merged in 2023-02, with the labels that each got.

#825 feat: default editor supports pasting or dragging pictures to upload
  package.json
  pnpm-lock.yaml
  src/components/editor/DefaultEditor.vue
Labels: kind/feature, release-note, approved, lgtm

#835 chore: release 2.2.0
  package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#836 fix: native login box pops up when the session expires
  src/utils/api-client.ts
Labels: release-note, approved, lgtm, area/console, kind/improvement

#838 fix: the width of the code input type is not full
  packages/components/src/components/codemirror/Codemirror.vue
Labels: release-note, approved, lgtm

#840 perf: fix CLS issue of actuator page
  src/modules/system/actuator/Actuator.vue
Labels: release-note, approved, lgtm, kind/improvement

#839 perf: improve usage of the card component in some pages
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
  src/modules/system/settings/layouts/SystemSettingsLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#845 fix: menu scroll bar is blocked
  src/layouts/BasicLayout.vue
Labels: release-note, approved, lgtm, area/console, kind/improvement

#844 perf: hide anonymousUser in user management list
  src/modules/system/users/UserList.vue
Labels: release-note, approved, lgtm, kind/improvement

#848 chore: fix lint issue
  src/components/editor/DefaultEditor.vue
  src/modules/dashboard/widgets/QuickLinkWidget.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#849 perf: improve the indexing threshold for the fuse search engine
  src/components/dropdown-selector/CategoryDropdownSelector.vue
  src/components/dropdown-selector/TagDropdownSelector.vue
  src/components/dropdown-selector/UserDropdownSelector.vue
  src/components/global-search/GlobalSearchModal.vue
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserList.vue
Labels: release-note, approved, lgtm, kind/improvement

#850 chore: add @LIlGG to reviewers list
  OWNERS
Labels: release-note-none, approved, lgtm, kind/improvement

#852 perf: improve word-break style for comment content
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
Labels: release-note, approved, lgtm, kind/improvement

#847 fix: the issue that role display name
  src/layouts/BasicLayout.vue
  src/main.ts
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserDetail.vue
  src/modules/system/users/UserList.vue
  src/stores/role.ts
Labels: release-note, approved, lgtm, kind/improvement

#857 perf: mute the fetch roles request
  src/stores/role.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#859 chore: release 2.2.1
  package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#851 perf: improve error message of login
  src/components/login/LoginForm.vue
Labels: release-note, approved, lgtm, kind/improvement

#860 chore: adjust the log level and delete useless logs
  packages/components/src/components/dialog/Dialog.story.vue
  src/components/form/AnnotationsForm.vue
  src/modules/contents/attachments/composables/use-attachment.ts
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/interface/menus/Menus.vue
  src/modules/system/users/components/GrantPermissionModal.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#861 feat: add layer-closeable prop for modal
  packages/components/src/components/dialog/Dialog.vue
  packages/components/src/components/modal/Modal.vue
  src/components/global-search/GlobalSearchModal.vue
  src/components/preview/UrlPreviewModal.vue
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  src/modules/contents/posts/components/PostPreviewModal.vue
  src/modules/dashboard/Dashboard.vue
Labels: kind/feature, release-note, approved, lgtm

#841 feat: add supports for preview audio and video file in attachment detail
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
Labels: kind/feature, release-note, approved, lgtm

#862 feat: user management supports conditional filtering and sorting
  packages/api-client/src/.openapi-generator/FILES
  packages/api-client/src/api/api-console-halo-run-v1alpha1-user-api.ts
  src/modules/system/users/UserList.vue
Labels: kind/feature, release-note, approved, lgtm

#864 perf: default editor's toc supports showing empty states
  src/components/editor/DefaultEditor.vue
Labels: release-note, approved, lgtm, kind/improvement

#867 feat: add supports for download log file in actuator page
  src/modules/system/actuator/Actuator.vue
Labels: kind/feature, release-note, approved, lgtm

#866 fix: hide the ghost user from the user list
  src/modules/system/users/UserList.vue
Labels: kind/bug, release-note-none, approved, lgtm

#871 feat: prompt to upgrade plugin when installing existing plugin
  src/components/upload/UppyUpload.vue
  src/modules/system/plugins/components/PluginUploadModal.vue
Labels: kind/feature, release-note, approved, lgtm

#872 feat: add supports for display database info in actuator page
  src/modules/system/actuator/Actuator.vue
  src/modules/system/actuator/types/index.ts
Labels: kind/feature, release-note, approved, lgtm

#869 perf: improve the layout of post tags
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
Labels: release-note, approved, lgtm, kind/improvement

#865 perf: add supports for storing navbar position
  src/layouts/BasicLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#870 feat: provide Chinese translation for the system's role template
  package.json
  pnpm-lock.yaml
  src/locales/index.ts
  src/locales/lang/zh.ts
  src/main.ts
  src/modules/system/roles/RoleDetail.vue
  src/modules/system/roles/components/RoleEditingModal.vue
Labels: kind/feature, release-note, approved, lgtm

#876 refactor: use tanstack query to refactor plugins fetching
  package.json
  pnpm-lock.yaml
  src/main.ts
  src/modules/system/plugins/PluginDetail.vue
  src/modules/system/plugins/PluginList.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#868 perf: improve the validation rules for username
  src/modules/system/users/components/UserEditingModal.vue
Labels: release-note, approved, lgtm, kind/improvement

#878 refactor: use tanstack query to refactor attachments-related fetching
  src/components/editor/DefaultEditor.vue
  src/modules/contents/attachments/AttachmentList.vue
  src/modules/contents/attachments/components/AttachmentDetailModal.vue
  src/modules/contents/attachments/components/AttachmentGroupList.vue
  src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  src/modules/contents/attachments/components/AttachmentUploadModal.vue
  src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  src/modules/contents/attachments/composables/use-attachment-group.ts
  src/modules/contents/attachments/composables/use-attachment-policy.ts
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#880 fix: default value of formkit schema is not initialize in annotation form
  src/components/form/AnnotationsForm.vue
Labels: kind/bug, release-note, approved, lgtm, area/console

#881 refactor: remove default cover from user profile page
  src/modules/system/users/layouts/UserProfileLayout.vue
Labels: release-note, approved, lgtm, kind/improvement

#879 refactor: use tanstack query to refactor post-related fetching
  src/components/dropdown-selector/CategoryDropdownSelector.vue
  src/components/dropdown-selector/TagDropdownSelector.vue
  src/formkit/inputs/category-select/CategorySelect.vue
  src/formkit/inputs/category-select/components/CategoryTag.vue
  src/formkit/inputs/category-select/components/SearchResultListItem.vue
  src/formkit/inputs/tag-select/TagSelect.vue
  src/modules/contents/posts/DeletedPostList.vue
  src/modules/contents/posts/PostList.vue
  src/modules/contents/posts/categories/CategoryList.vue
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/categories/utils/index.ts
  src/modules/contents/posts/tags/TagList.vue
  src/modules/contents/posts/tags/composables/use-post-tag.ts
  src/modules/contents/posts/widgets/RecentPublishedWidget.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#882 refactor: request api of user data
  packages/api-client/src/.openapi-generator/FILES
  packages/api-client/src/api/api-console-halo-run-v1alpha1-user-api.ts
  packages/api-client/src/models/detailed-user.ts
  packages/api-client/src/models/index.ts
  packages/api-client/src/models/listed-user-list.ts
  packages/api-client/src/models/listed-user.ts
  src/layouts/BasicLayout.vue
  src/main.ts
  src/modules/system/roles/RoleList.vue
  src/modules/system/users/UserDetail.vue
  src/modules/system/users/UserList.vue
  src/modules/system/users/layouts/UserProfileLayout.vue
  src/stores/role.ts
  src/stores/user.ts
Labels: release-note, approved, lgtm, kind/improvement

#883 perf: improve the conditions for categories and tags automatic refresh
  src/modules/contents/posts/categories/composables/use-post-category.ts
  src/modules/contents/posts/tags/composables/use-post-tag.ts
Labels: release-note, approved, lgtm, kind/improvement

#884 fix: the issue that the useSlugify hook may cause the value to be undefined
  src/composables/use-slugify.ts
Labels: kind/bug, release-note, approved, lgtm

#863 feat: editor supports selecting attachments to be inserted as links
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/feature, release-note, approved, lgtm

#873 perf: disable the editor from pasting excel tables as pictures
  src/components/editor/DefaultEditor.vue
Labels: release-note, approved, lgtm, kind/improvement

#874 refactor: change the creation time field for comments and replies
  packages/api-client/src/models/comment-spec.ts
  packages/api-client/src/models/reply-spec.ts
  src/modules/contents/comments/components/CommentListItem.vue
  src/modules/contents/comments/components/ReplyListItem.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#875 refactor: support configuring plugin when the plugin is stopped
  packages/api-client/src/models/plugin-status.ts
  src/modules/system/plugins/components/PluginListItem.vue
  src/modules/system/plugins/layouts/PluginLayout.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#877 perf: hide active button when theme is activated
  src/modules/interface/themes/components/components/ThemeListItem.vue
  src/modules/interface/themes/components/preview/ThemePreviewListItem.vue
Labels: release-note, approved, lgtm, kind/improvement

#885 fix: user filter list will fail to load the avatar after searching
  src/components/dropdown-selector/UserDropdownSelector.vue
Labels: kind/bug, release-note, approved, lgtm

#888 chore: release 2.3.0-rc.1
  package.json
  packages/api-client/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#889 fix: pages using tanstack query cannot be loaded in production build
  package.json
  pnpm-lock.yaml
  src/build/library-external.ts
Labels: kind/bug, release-note-none, approved, lgtm

#894 feat: add supports for initialize preset plugins
  packages/api-client/src/api/api-console-halo-run-v1alpha1-plugin-api.ts
  packages/api-client/src/base.ts
  packages/api-client/src/models/plugin-status.ts
  src/views/system/Setup.vue
Labels: kind/feature, release-note, approved, lgtm

#890 fix: incorrect default pagination number of attachment list
  src/modules/contents/attachments/AttachmentList.vue
Labels: kind/bug, release-note-none, approved, lgtm

#895 perf: add success toast for saving plugin and theme settings
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  src/modules/system/plugins/PluginSetting.vue
Labels: release-note-none, approved, lgtm, kind/improvement

#893 fix: get the wrong link after selecting an attachment
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/bug, release-note-none, approved, lgtm

#896 chore: release 2.3.0
  package.json
  packages/api-client/package.json
  packages/components/package.json
  packages/shared/package.json
Labels: release-note-none, approved, lgtm, kind/improvement

#892 refactor: use tanstack query to refactor comment-related fetching
  src/modules/contents/comments/CommentList.vue
  src/modules/contents/comments/components/CommentListItem.vue
Labels: release-note-none, approved, lgtm, kind/improvement
