Repository halo-dev/console, pull requests merged in 2023-01, with the labels that each got.

#813 fix: timeout error caused by upload processing for more than 30 seconds
  src/components/upload/UppyUpload.vue
Labels: release-note, approved, lgtm, kind/improvement

#816 refactor: refactor the page management and remove the function page
  packages/shared/src/states/pages.ts
  packages/shared/src/types/plugin.ts
  src/modules/contents/pages/FunctionalPageList.vue
  src/modules/contents/pages/SinglePageList.vue
  src/modules/contents/pages/layouts/PageLayout.vue
  src/modules/contents/pages/module.ts
Labels: release-note, approved, kind/api-change, lgtm, kind/improvement

#819 chore: bump vite version to 4
  package.json
  pnpm-lock.yaml
Labels: release-note, approved, lgtm, kind/improvement

#817 feat: add full-functional post tag select component for formkit
  docs/custom-formkit-input/README.md
  src/formkit/formkit.config.ts
  src/formkit/inputs/tag-select.ts
  src/formkit/inputs/tag-select/TagSelect.vue
  src/formkit/inputs/tag-select/index.ts
  src/formkit/inputs/tag-select/sections/index.ts
  src/formkit/theme.ts
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/PostTag.vue
Labels: kind/feature, release-note, approved, lgtm

#821 feat: update comment list sorter
  src/modules/contents/comments/CommentList.vue
Labels: kind/feature, release-note, approved, lgtm

#822 feat: make sidebar logo link to home page
  src/layouts/BasicLayout.vue
Labels: kind/feature, release-note, approved, lgtm

#823 perf: improve plugin loading
  src/main.ts
Labels: release-note, approved, lgtm, kind/improvement

#827 perf: change attachment list layout to list mode
  src/modules/contents/attachments/AttachmentList.vue
Labels: release-note, approved, lgtm, kind/improvement

#826 feat: update theme requires field and supports show failed message
  package.json
  pnpm-lock.yaml
  src/modules/interface/themes/ThemeDetail.vue
  src/modules/interface/themes/components/components/ThemeListItem.vue
  src/modules/interface/themes/composables/use-theme.ts
Labels: kind/feature, release-note, approved, lgtm

#830 fix: use comment.metadata.name instead of index as the key of comments list
  src/modules/contents/comments/CommentList.vue
Labels: kind/bug, release-note, approved, lgtm

#829 fix: add word break for long toast body
  packages/components/src/components/toast/Toast.vue
Labels: kind/bug, release-note, approved, lgtm

#820 refactor: use new apis to refactor themes management
  src/components/global-search/GlobalSearchModal.vue
  src/composables/use-setting-form.ts
  src/main.ts
  src/modules/dashboard/widgets/QuickLinkWidget.vue
  src/modules/interface/themes/ThemeSetting.vue
  src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  src/modules/interface/themes/composables/use-theme.ts
  src/modules/interface/themes/layouts/ThemeLayout.vue
  src/modules/interface/themes/module.ts
  src/stores/theme.ts
Labels: release-note, approved, lgtm, kind/improvement

#831 feat: add supports for automatic slug generation
  package.json
  pnpm-lock.yaml
  src/composables/use-slugify.ts
  src/formkit/inputs/category-select/CategorySelect.vue
  src/formkit/inputs/tag-select/TagSelect.vue
  src/modules/contents/pages/components/SinglePageSettingModal.vue
  src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  src/modules/contents/posts/components/PostSettingModal.vue
  src/modules/contents/posts/tags/components/TagEditingModal.vue
Labels: kind/feature, release-note, approved, lgtm

#828 refactor: change api of fetching post and singlepage content
  package.json
  pnpm-lock.yaml
  src/modules/contents/pages/SinglePageEditor.vue
  src/modules/contents/posts/PostEditor.vue
  src/utils/api-client.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#832 feat: add actuator view page
  packages/components/src/icons/icons.ts
  src/modules/index.ts
  src/modules/system/actuator/Actuator.vue
  src/modules/system/actuator/module.ts
  src/modules/system/actuator/types/index.ts
Labels: kind/feature, release-note, approved, lgtm

#834 chore: bump @halo-dev/richtext-editor to supports more feature about media
  .npmrc
  package.json
  pnpm-lock.yaml
  src/components/editor/DefaultEditor.vue
  src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/feature, release-note, approved, lgtm
